---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfluxbasicapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webfluxbasicapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: webfluxbasicapi
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: webfluxbasicapi
          image: webfluxapiserviceregistry.azurecr.io/webfluxbasicapi:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: webfluxbasicapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webfluxbasicapi


---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webfluxbasicapi-hpa
spec:
  maxReplicas: 3 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webfluxbasicapi
  targetCPUUtilizationPercentage: 50 # target CPU utilization